services:
  web:
    build: .
    ports:
      - "127.0.0.1:${DJANGO_PORT}:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
