# Generated by Django 6.1.1 on 2026-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('idea_title', models.CharField(max_length=200)),
                ('idea_pdf', models.FileField(blank=True, max_length=255, upload_to='ideas/pdfs/')),
                ('idea_github', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=20)),
                ('idea_consent', models.BooleanField(default=False)),
                ('consent_version', models.CharField(default='1.0', max_length=20)),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
