# Generated by Django 6.1.1 on 2026-09-25 14:31

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasubmission',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='idea_pdf',
            field=models.FileField(blank=True, max_length=255, upload_to=home.models.idea_pdf_upload_path),
        ),
    ]
