# Generated by Django 6.1.1 on 2026-09-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_ideasubmission_contact_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Em análise'), (2, 'Em desenvolvimento'), (3, 'Concluída')], default=1),
        ),
    ]
