# Generated by Django 6.1.1 on 2026-09-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ideasubmission_is_featured_ideasubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='idea_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
