# Generated by Django 6.1.1 on 2026-10-02 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ideasubmission_idea_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=100, verbose_name='Nome ou pseudônimo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='E-mail confirmado em')),
                ('contact_preference', models.CharField(choices=[('none', 'Não desejo contato'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='none', max_length=10, verbose_name='Preferência de contato')),
                ('contact_authorized', models.BooleanField(default=False, verbose_name='Autoriza contato sobre contribuições')),
                ('contact_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Autorização de contato registrada em')),
                ('consent_version', models.CharField(default='1.0', max_length=20)),
                ('can_publish_directly', models.BooleanField(default=False, verbose_name='Pode publicar sem aprovação')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Participação bloqueada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=10000, verbose_name='Mensagem')),
                ('github_url', models.URLField(blank=True, max_length=500, verbose_name='GitHub')),
                ('status', models.CharField(choices=[('pending', 'Aguardando aprovação'), ('published', 'Publicado'), ('reported', 'Oculto por denúncias'), ('disabled', 'Desativado pela administração')], default='pending', max_length=12)),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Removido pelo autor em')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True, verbose_name='Observação interna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='home.collaborator', verbose_name='Autor')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.ideasubmission', verbose_name='Ideia')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='home.comment', verbose_name='Comentário respondido')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam ou publicidade'), ('abuse', 'Ofensa ou assédio'), ('unsafe', 'Conteúdo ou link perigoso'), ('other', 'Outro motivo')], max_length=10, verbose_name='Motivo')),
                ('details', models.TextField(blank=True, max_length=1000, verbose_name='Detalhes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Avaliada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.comment', verbose_name='Comentário')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='home.collaborator', verbose_name='Denunciante')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['idea', 'status', 'created_at'], name='home_commen_idea_id_eb029b_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(condition=models.Q(('reviewed_at__isnull', True)), fields=['comment'], name='pending_comment_reports'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reporter'), name='unique_report_per_comment_and_user'),
        ),
    ]
