# Generated by Django 6.1.1 on 2026-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_collaborator_comment_commentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última confirmação enviada em'),
        ),
    ]
