# Generated by Django 6.1.1 on 2026-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_collaborator_confirmation_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ideia ativa'),
        ),
    ]
