# Generated by Django 6.1.1 on 2026-10-07 14:23

from django.db import migrations, models


def preserve_existing_publication(apps, schema_editor):
    apps.get_model("home", "IdeaSubmission").objects.using(schema_editor.connection.alias).update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ideasubmission_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Denúncia descartada'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='review_note',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Motivo da avaliação'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Publicação aprovada'),
        ),
        migrations.RunPython(preserve_existing_publication, migrations.RunPython.noop),
    ]
