# Generated by Django 6.1.1 on 2026-10-07 14:41

import django.db.models.deletion
import home.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_commentreport_dismissed_commentreport_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('pdf', models.FileField(blank=True, storage=home.storage.PrivateDraftStorage(), upload_to='drafts/')),
                ('pdf_name', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingFileDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ideasubmission')),
            ],
        ),
    ]
